stages:
  train_pipeline:
    cmd: python main.py

    deps:
      - data/raw/Dry_Bean_Dataset.csv
      - src/preprocessing.py
      - src/train.py
      - src/evaluate.py
      - src/utils.py
      - main.py

    outs:
      - models/random_forest.pkl
      - models/adaboost.pkl